name: Build and Push

on:
  push:
    branches: ["master"]

env:
  AWS_REGION: ap-south-1

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./infrastructure/main_infra/

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./infrastructure/main_infra/

      - name: Get ECR URLs from Terraform
        id: get-ecr
        run: |
          SERVICE_A_URL=$(aws ecr describe-repositories --repository-names service-a --query "repositories[0].repositoryUri" --output text)
          SERVICE_B_URL=$(aws ecr describe-repositories --repository-names service-b --query "repositories[0].repositoryUri" --output text)
          echo "service_a_url=$SERVICE_A_URL" >> $GITHUB_OUTPUT
          echo "service_b_url=$SERVICE_B_URL" >> $GITHUB_OUTPUT

      - name: Build & Push Service A
        run: |
          docker build -t ${{ steps.get-ecr.outputs.service_a_url }}:${{ github.sha }} ./micro-services-app/service-a/
          docker push ${{ steps.get-ecr.outputs.service_a_url }}:${{ github.sha }}

      - name: Build & Push Service B
        run: |
          docker build -t ${{ steps.get-ecr.outputs.service_b_url }}:${{ github.sha }} ./micro-services-app/service-b/
          docker push ${{ steps.get-ecr.outputs.service_b_url }}:${{ github.sha }}

      # - name: Destroy Infrastructure
      #   run: terraform destroy --auto-approve
      #   working-directory: ./infrastructure
